### ISSUE TITLE
Phantom Nodes

### ISSUE THREAD

**Issue by DaveStLou** [UniversalDevicesInc-PG3/udi-harmony-poly#34]
After installing the PG3 version, I found two phantom nodes that are not part of my system. Based on the detail in the drop down, I suspect they are part of a test or development system. They can easily be deleted but may confuse novice users.

![Phantom-FamilyRoom-Node](https://user-images.githubusercontent.com/16002402/149514851-7a9eef13-a643-41df-b34e-cfc6e90fba22.png)
![Phantom-MasterBedroom-Node](https://user-images.githubusercontent.com/16002402/149514853-06edda82-ecd4-4f42-8a3b-d30cc9b950f4.png)

**Comment by DaveStLou** [comment]
Additional information: They do reappear after nodeserver restart.

**Comment by jimboca** [comment]
Thanks, will try to look into it this morning.

**Comment by jimboca** [comment]
The only place those show up in my code is in comments.  Can you check your configuration in the Polyglot UI and make sure you don't have something defined?  Also, when you delete the nodes, delete them in the Polyglot UI, not the admin console.

There is also a bug in PG3 currently if you restart the nodeserver then your node addresss may change...  Next version of PG3 should fix that.

**Comment by DaveStLou** [comment]
There's nothing in my Polyglot configuration. I used the Polyglot UI to delete them. I will send my logs via forum DM.

**Comment by jimboca** [comment]
I found the issue, can't fix until tomorrow

**Comment by jimboca** [comment]
Fixed in the release, but didn't change the version number.  I think PG3 re-downloads on each restart but I'm waiting for confirmation on that from Bob.

**Comment by jimboca** [comment]
I released 3.0.3 which should fix this, so just restart and they won't show up again.
